# Generated by Django 4.2.6 on 2023-11-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contato',
            new_name='contatom',
        ),
    ]
