# Generated by Django 4.2.6 on 2023-11-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_contato_contatom'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_pet', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('dia_da_reserva', models.CharField(max_length=50)),
                ('observaçao', models.TextField(blank=True, verbose_name='observaçao')),
            ],
        ),
    ]
