# Generated by Django 4.2.6 on 2023-11-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_reserva'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reserva',
            new_name='reservam',
        ),
    ]
