# Generated by Django 4.2.6 on 2023-11-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_reserva_reservam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatom',
            options={'ordering': ['-data'], 'verbose_name': 'formulario de contato', 'verbose_name_plural': 'formulario de contatos'},
        ),
        migrations.AddField(
            model_name='contatom',
            name='lido',
            field=models.BooleanField(blank=True, default=False, verbose_name='lido'),
        ),
        migrations.AlterField(
            model_name='contatom',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='contatom',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contatom',
            name='mensagem',
            field=models.TextField(verbose_name='mensagem'),
        ),
        migrations.AlterField(
            model_name='contatom',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
    ]
