# Generated by Django 4.2.6 on 2023-11-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_rename_data_reserva_data_reserva_alter_reserva_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data_reserva',
            new_name='data',
        ),
    ]
